[project]
name = "failure-time-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <4.0"
dependencies = ["flowcean"]

[tool.pyright]
extends = "../../pyproject.toml"

[tool.uv.sources]
flowcean = { path = "../.." }
