#
# Build stage
#
FROM docker.io/library/maven:3.9.6-eclipse-temurin-21-jammy AS build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
ADD . $HOME
RUN mvn -f $HOME/pom.xml clean compile assembly:single

#
# Package stage
#
FROM docker.io/library/eclipse-temurin:21-jre-jammy
ARG JAR_FILE=/usr/app/target/*.jar
COPY --from=build $JAR_FILE /app/app.jar
EXPOSE 8080
ENTRYPOINT java -jar /app/app.jar
