site_name: Flowcean
repo_url: https://github.com/flowcean/flowcean
repo_name: flowcean/flowcean

theme:
  name: "material"
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            merge_init_into_class: true
            members_order: source
  - search
  - gen-files:
      scripts:
        - scripts/generate_reference_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

watch:
  - src

nav:
  - Flowcean: index.md
  - Research Project: agenc/
  - Getting Started:
    - Preparation: getting_started/preparation.md
    - Installation: getting_started/installation.md
    - New Project: getting_started/new_project.md
    - Documentation: getting_started/documentation.md
    - DVC: getting_started/dvc.md
  - User Guide:
    - Overview: user_guide/overview.md
    - Modules: user_guide/modules.md
    - Environment: user_guide/environment.md
    - Transform: user_guide/transform.md
    - Learning Strategies: user_guide/learning_strategies.md
    - Model: user_guide/model.md
    - Evaluation: user_guide/evaluation.md
    - Experiment: user_guide/experiment.md
    - Tools: user_guide/tools.md
  - Examples:
    - Coffee Machine: examples/coffee_machine.md
    - Failure Time Prediction: examples/failure_time_prediction.md
    - One Tank: examples/one_tank.md
  - Reference: reference/
