[default]
extend-words = { CPY = "CPY" }
extend-ignore-words-re = [
  "MAPE", # MeanAveragePercentageError
  "TPE",  # TreeParzenEstimator
]
extend-ignore-identifiers-re = [
  "NDArray", # NumPy type alias
  "arange",  # NumPy function
]
