# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import learner_pb2 as learner__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/flowcean/grpc/proto/learner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearnerStub(object):
    """The Learner service provides RPCs for training, prediction, and export.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_stream(
                '/Learner/Train',
                request_serializer=learner__pb2.DataPackage.SerializeToString,
                response_deserializer=learner__pb2.StatusMessage.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/Learner/Predict',
                request_serializer=learner__pb2.DataPackage.SerializeToString,
                response_deserializer=learner__pb2.Prediction.FromString,
                _registered_method=True)
        self.Export = channel.unary_unary(
                '/Learner/Export',
                request_serializer=learner__pb2.Empty.SerializeToString,
                response_deserializer=learner__pb2.Empty.FromString,
                _registered_method=True)


class LearnerServicer(object):
    """The Learner service provides RPCs for training, prediction, and export.
    """

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_stream_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.DataPackage.FromString,
                    response_serializer=src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.StatusMessage.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.DataPackage.FromString,
                    response_serializer=src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.Prediction.SerializeToString,
            ),
            'Export': grpc.unary_unary_rpc_method_handler(
                    servicer.Export,
                    request_deserializer=src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.Empty.FromString,
                    response_serializer=src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Learner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Learner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Learner(object):
    """The Learner service provides RPCs for training, prediction, and export.
    """

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Learner/Train',
            src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.DataPackage.SerializeToString,
            src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.StatusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Learner/Predict',
            src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.DataPackage.SerializeToString,
            src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Export(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Learner/Export',
            src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.Empty.SerializeToString,
            src_dot_flowcean_dot_grpc_dot_proto_dot_learner__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
