[project]
name = "active-learning"
version = "0.1.0"
requires-python = ">=3.10, <4.0"
dependencies = ["flowcean"]

[tool.pyright]
extends = "../../pyproject.toml"

[tool.uv.sources]
flowcean = { workspace = true }
