"""Hybrid-system modeling, automaton diagrams, simulation, and traces."""

from . import benchmarks, hydra
from .graph import build_hybrid_system_dot, render_dot_svg
from .hybrid_system import (
    ContinuousDynamics,
    CrossingDirection,
    Event,
    EventSurface,
    EventSurfaceFunction,
    FlowFunction,
    HybridSystem,
    Input,
    InputStream,
    Location,
    Parameters,
    Reset,
    ResetFunction,
    SurfaceEntryPolicy,
    Trace,
    Transition,
)
from .io import (
    save_traces_csv,
    save_traces_parquet,
    trace_to_polars,
    traces_to_polars,
)
from .plotting import plot_locations, plot_phase, plot_trace
from .simulator import (
    AmbiguousTransitionError,
    HybridSimulationError,
    InvalidEventSurfaceValueError,
    SimulationProgressError,
    SurfaceEntryError,
    generate_traces,
    simulate,
)

__all__ = (
    "AmbiguousTransitionError",
    "ContinuousDynamics",
    "CrossingDirection",
    "Event",
    "EventSurface",
    "EventSurfaceFunction",
    "FlowFunction",
    "HybridSimulationError",
    "HybridSystem",
    "Input",
    "InputStream",
    "InvalidEventSurfaceValueError",
    "Location",
    "Parameters",
    "Reset",
    "ResetFunction",
    "SimulationProgressError",
    "SurfaceEntryError",
    "SurfaceEntryPolicy",
    "Trace",
    "Transition",
    "benchmarks",
    "build_hybrid_system_dot",
    "generate_traces",
    "hydra",
    "plot_locations",
    "plot_phase",
    "plot_trace",
    "render_dot_svg",
    "save_traces_csv",
    "save_traces_parquet",
    "simulate",
    "trace_to_polars",
    "traces_to_polars",
)
