# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: externalFramework.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xternalFramework.proto\"\x17\n\x07\x44\x61taRow\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"a\n\x0e\x43olumnMetaData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nlowerBound\x18\x02 \x01(\x01\x12\x12\n\nupperBound\x18\x03 \x01(\x01\x12\x19\n\x04type\x18\x04 \x01(\x0e\x32\x0b.ColumnType\"V\n\x0b\x44\x61taPackage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x08metaData\x18\x02 \x03(\x0b\x32\x0f.ColumnMetaData\x12\x16\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x08.DataRow\"c\n\x0bLearnerData\x12\x12\n\nreturnCode\x18\x01 \x01(\x05\x12\x1a\n\rresultMessage\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nidentifier\x18\x03 \x01(\x05\x42\x10\n\x0e_resultMessage*S\n\nColumnType\x12\x18\n\x14\x43OLUMNTYPE_UNDEFINED\x10\x00\x12\x14\n\x10\x43OLUMNTYPE_INPUT\x10\x01\x12\x15\n\x11\x43OLUMNTYPE_TARGET\x10\x02\x32\x63\n\x0f\x45xternalLearner\x12,\n\x0cTrainLearner\x12\x0c.DataPackage\x1a\x0c.LearnerData\"\x00\x12\"\n\nRunLearner\x12\x08.DataRow\x1a\x08.DataRow\"\x00\x42\x1c\n\x1aio.agenc.externalframeworkb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'externalFramework_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032io.agenc.externalframework'
  _COLUMNTYPE._serialized_start=340
  _COLUMNTYPE._serialized_end=423
  _DATAROW._serialized_start=27
  _DATAROW._serialized_end=50
  _COLUMNMETADATA._serialized_start=52
  _COLUMNMETADATA._serialized_end=149
  _DATAPACKAGE._serialized_start=151
  _DATAPACKAGE._serialized_end=237
  _LEARNERDATA._serialized_start=239
  _LEARNERDATA._serialized_end=338
  _EXTERNALLEARNER._serialized_start=425
  _EXTERNALLEARNER._serialized_end=524
# @@protoc_insertion_point(module_scope)
