# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import externalFramework_pb2 as externalFramework__pb2


class ExternalLearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainLearner = channel.unary_unary(
                '/ExternalLearner/TrainLearner',
                request_serializer=externalFramework__pb2.DataPackage.SerializeToString,
                response_deserializer=externalFramework__pb2.LearnerData.FromString,
                )
        self.RunLearner = channel.unary_unary(
                '/ExternalLearner/RunLearner',
                request_serializer=externalFramework__pb2.DataRow.SerializeToString,
                response_deserializer=externalFramework__pb2.DataRow.FromString,
                )


class ExternalLearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainLearner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunLearner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalLearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainLearner': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainLearner,
                    request_deserializer=externalFramework__pb2.DataPackage.FromString,
                    response_serializer=externalFramework__pb2.LearnerData.SerializeToString,
            ),
            'RunLearner': grpc.unary_unary_rpc_method_handler(
                    servicer.RunLearner,
                    request_deserializer=externalFramework__pb2.DataRow.FromString,
                    response_serializer=externalFramework__pb2.DataRow.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExternalLearner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExternalLearner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainLearner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExternalLearner/TrainLearner',
            externalFramework__pb2.DataPackage.SerializeToString,
            externalFramework__pb2.LearnerData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunLearner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExternalLearner/RunLearner',
            externalFramework__pb2.DataRow.SerializeToString,
            externalFramework__pb2.DataRow.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
