name: Build and Push Java Image

on:
  push:
      branches:
        - update-coffee
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: java-automata-learner

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah
      - name: Log in to GitHub Container Registry
        env:
          REGISTRY_URL: ghcr.io
        run: |
          buildah login --username "${{ github.actor }}" \
                        --password "${{ secrets.GITHUB_TOKEN }}" \
                        ${{ env.REGISTRY }}
      - name: Build Container Image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-app
        run: |
          buildah build --tag "java-automata-learner:latest" -f Containerfile java/AutomataLearner
      - name: Push Container Image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/java-automata-learner
        run: |
          buildah push "java-automata-learner:latest"
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
