name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: Publish
    runs-on:
      - self-hosted
      - itl
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Set up just
        uses: extractions/setup-just@v4

      - name: Validate release version
        id: version
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          VERSION=${TAG_NAME#v}
          PROJECT_VERSION=$(uv version --short)
          if [[ "$VERSION" != "$PROJECT_VERSION" ]]; then
            echo "Tag version $VERSION does not match project version $PROJECT_VERSION" >&2
            exit 1
          fi
          # Check if the version has a pre-release segment (a, b, or rc followed by digits)
          # or a developmental release segment (".dev" followed by digits).
          if [[ "$VERSION" =~ ((a|b|rc)[0-9]+)|(\.dev[0-9]+) ]]; then
            IS_PRERELEASE=true
          else
            IS_PRERELEASE=false
          fi
          echo "is_prerelease=$IS_PRERELEASE" >> "$GITHUB_OUTPUT"

      - name: Check lock file
        run: just check-uv

      - name: Build package distributions
        run: just package

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: ${{ steps.version.outputs.is_prerelease }}
          files: |
            dist/flowcean-*.tar.gz

      - name: Publish package
        run: uv publish
